Guess Who- game
Technigo/project-guess-who pull request #27
Opened 2021-02-14 09:10 UTC by malinvan

guesswhogame-mvan.netlify.app

2021-02-16 17:02 UTC, matildasvensson85 requested changes
Great work! You met all requirements for blue level and most of the requirements for the red level. You added lot of new options to choose from in the dropdown-menu that made the game easier and more fun to play. 

In general I think the code looks great, its indentation is good, its tidy and easy to understand,  the structure is logical and you use variable names in a way that makes the code easy to read. In most cases everything is coherent (some exceptions in the comment I added). You also just used let (vs const) when needed to. Even though you wrote you didn't have time for styling, I see you did some minor changes in the css well. Great work!

2021-02-20 18:42 UTC, KarolCislowski commented on code/script.js
> +  console.log(secret);
Yes, remember to always clean your code from all console.log()s and commented out code blocks and tips left for you by teachers 🗡️ ✂️

2021-02-20 18:44 UTC, KarolCislowski commented on code/script.js
> +  setSecret();
Remember that you can set your VScode to insert all needed semicolons for you. Go to settings, search for a semicolon and choose it 🤖 🦾

2021-02-20 18:50 UTC, KarolCislowski approved these changes
This is a very nice project 🌈 

I know it was an extra point of this assignment to style it your way but remember that there is no another way to master CSS then practice it over and over again 🦾 

Remember that you can always come back to it when you have some spare time and add more functionalities to make it an even greater portfolio asset! 🦄

2021-02-20 18:50 UTC, KarolCislowski commented on code/script.js
> +      innerText: selectedElementInnerText,
It is not a good practice to name fields the same way that DOM functions or fields.

2021-08-10 13:01 UTC, closed without merging