Guess who - Maria Pogosjan
Technigo/project-guess-who pull request #34
Opened 2021-02-14 12:48 UTC by MariaPogosjan

Hi! 

**As you can see I kept the same layout. However I made some changes with the css:** 
- I made different background colors in checkMyGuess, depending if the users guesses right (green) or wrong (red).
- Made some buttons smaller
- Added some small changes so it would look better in mobile size.  
- I also added <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"> in my HTML to be able to use Sweetalert's custom alert messages. Therefore on my JS I don't have "alert" in some places, instead "swal"

**Problems I couldn't solve:** 
- The timer starts from the beginning when the prompt message appairs, I couldn't manage to solve that. 
- The sound effects have some delay on mobile version, why?

2021-02-15 16:02 UTC, klimenko3007 requested changes
I think you did a fantastic job using a lot of advanced code we have not learned about! I am really impressed! Cool sound effects! 
I think though it is important to change the wrongGuess value in your start function. Otherwise the game does not work how it should.

2021-02-16 09:25 UTC, MariaPogosjan commented on code/script.js
>  }
Thank you for noticing it! I have accidentally deleted the wrongGuess from start. I added it back and it works now.

2021-02-16 09:29 UTC, MariaPogosjan commented on code/style.css
> +  }
I tried to look at this but I can't see that the numbers are jumping on big screen or mobile. I looked a both but can't find the same problem. Could you describe where you see this? :)

2021-02-20 20:58 UTC, KarolCislowski approved these changes
This is a very impressive project! 🌈  You have shown great ambition 🦄 

I think the issue with the sound on mobile phones is due to the different access to the sound system. You can play sounds at once on the computer, and mobiles need to queue them.

2021-02-20 20:58 UTC, KarolCislowski commented on code/script.js
> +    man: true,
Nice that you decide to experiment with the given data 🥼

2021-02-20 20:58 UTC, KarolCislowski commented on code/script.js
> +  showGuessCount()
you can try to move your timer here after all alerts already happend 🤓

2021-02-20 20:58 UTC, KarolCislowski commented on code/style.css
> +  }
`overflow: hidden;` should make a trick with hiding scrollbars 🤓

2021-08-10 13:01 UTC, closed without merging