Project 5, Guess Who / Anna-Kaisa Honkonen
Technigo/project-guess-who pull request #38
Opened 2021-02-14 17:47 UTC by honkoan

https://guess-who-honkoan.netlify.app/

2021-02-16 19:35 UTC, Irina-web-dev requested changes
Awesome project and great job. It was easy to read your code, everything is clean and clear. I can see that you have applied knowledge gained through the code sessions, for example, you have used objects shorthand in your project.  It is good to start applying this knowledge and skills from the very beginning.

Below I have provided some tips about using comments and console.logs.

And I have noticed that "smoker" filtering is not working in the game. Due to that I would ask you to make changes before approval.  I have also provided advice for this problem.

2021-02-16 19:35 UTC, Irina-web-dev commented on code/script.js
> +    currentQuestion = {
You are missing property "attribute: actualValue " here. This might be the reason why smoking filtering is not working in the game.

2021-02-16 19:35 UTC, Irina-web-dev commented on code/script.js
> +  } else if (category === 'other') {
Smoking filtering is not working. One reason is that you haven´t defined "attribute: actualValue " property (see my comment in line 298). And here similar approach as for other categories´ alert messages should be used: 
 
else if (category === 'other') {
 if (keep) {
      alert(
        `Yes, the person is a ${currentQuestion.attribute}! Keep all persons who are ${attribute}`
 )
    } else {
      alert(
        `No, the person is not a ${currentQuestion.attribute}! Remove all persons who are not ${attribute}`
      )
    }

2021-02-20 21:51 UTC, KarolCislowski approved these changes
This is a very nice project 🌈 

Remember that you can always come back to it when you have some spare time and add more functionalities to make it an even greater portfolio asset! 🦄 

It's great that you followed your friends tips. It is very important to act after receiving the review 🥳

2021-02-20 21:51 UTC, KarolCislowski commented on code/script.js
>  const filterCharacters = (keep) => {
You creating the `keep` here, so this function does not use the global one. There is no use in storing extra global copy then 🤓

2021-08-10 13:00 UTC, closed without merging