last
Technigo/project-guess-who pull request #47
Opened 2021-02-14 20:30 UTC by nazi-pira

2021-02-17 23:01 UTC, sarianne-peltola approved these changes
I very much enjoyed reviewing this! Great job! Just some minor things that I noticed, just a little bit indentation in the html. Some coloring in the css. And perhaps a bit some changes in the js. Nice work :) :)

2021-02-20 23:17 UTC, KarolCislowski requested changes
Your code looks great, but to test it I need a link to the hosted version. 🌈 

Please provide it and while doing it make your ReadMe file shine like a diamond 💎

2021-02-20 23:17 UTC, KarolCislowski commented on code/script.js
> +    button: false
It is nice that you experimented with the data provided by the teachers. 👍🏻

2021-02-20 23:17 UTC, KarolCislowski commented on code/script.js
> +  console.log(secret);
Yes, remember to always clean your code from all console.log()s and commented out code blocks and tips left for you by teachers 🗡️ ✂️

2021-04-24 16:30 UTC, nazi-pira commented
console.log deleted and netlify link updated

2021-05-17 23:56 UTC, KarolCislowski approved these changes
Great App 🥇

2021-08-10 13:00 UTC, closed without merging