Guess Who Tobias Hagberg, Jan 21
Technigo/project-guess-who pull request #59
Opened 2021-02-17 07:16 UTC by TobiasHagberg

2021-02-17 20:35 UTC, sirimatsdotter requested changes
Great job Tobias, the game works great and I like the color you chose!🙂

Not sure if this was a mandatory requirement but  the win or loose section does not display after doing the final guess (I will leave that for the code coaches to judge if this was a mandatory step), but I think it could be a good idea to try to implement if you have time. It seems like you tried to display the section, but at the same time you used an alert which is a popup and won't display the message in the win or loose section...

Also, after the final guess the page does not reload, which might be a good idea to implement for the user. I saw that you wrote about that you implemented the "play again" in your readme, but I cannot see that it is implemented on your live site.

2021-02-17 20:35 UTC, sirimatsdotter commented on code/script.js
> +    winOrLose.style.display = 'block'
So this triggers an alert, but I cannot see the winorloose section. I think perhaps that you should exclude the alert and instead place your message inside the win or loose section by using .innerHTML.

2021-02-17 20:35 UTC, sirimatsdotter commented on code/script.js
> +playAgainButton.addEventListener('click', start)
The play again button is not visible since the win or loose section never appears

2021-02-17 20:35 UTC, sirimatsdotter commented on code/style.css
> +  --secondary: #32575D;
I loved learning about how one can set key colors using --primary and --secondary - makes it so much easier to change the look in just a few seconds!

2021-02-17 20:35 UTC, sirimatsdotter commented on README.md
> +The approach was slow but steady, tried to take in as much as possible of provided material and made a handdrawn sketch of the flow before attempting it in code. I follewed the step by step guide and
I think it's a great idea to sketch it first by hand 😍

2021-02-17 20:35 UTC, sirimatsdotter commented on README.md
> +I find myself always wanting an perhaps needing more time. all and all, I'm happy that my game is working. If I have had more time I would have put it into styling and extra effects for more fun
I think we all need more time 😅 But you have made the game work which is a great achievement by itself!

2021-02-17 20:35 UTC, sirimatsdotter commented on README.md
> +https://gracious-ritchie-308aae.netlify.app/
It's looking great, but I can't see the win or loose section, instead there is an alert message

2021-02-21 01:14 UTC, KarolCislowski approved these changes
This is a very nice project 🌈 Hope my tips will help you with your minor issues 🤓 

Remember that you can always come back to it when you have some spare time and add more functionalities to make it an even greater portfolio asset! 🦄

2021-02-21 01:14 UTC, KarolCislowski commented on code/script.js
> +    board.innerHTML = ''
`bord.style.display='none'` would do the magic 🧙🏻

2021-02-21 01:14 UTC, KarolCislowski commented on code/script.js
> +  winOrLose.style.display = ''
If you decide to make changes I suggested at the end of the code, you need to make some here as well:
```
winOrLose.style.display = 'none'
board.style.display='flex'
```

2021-08-10 13:00 UTC, closed without merging