Guess who game
Technigo/project-guess-who pull request #9
Opened 2021-02-12 16:34 UTC by matildasvensson85

2021-02-15 18:00 UTC, jesinkey requested changes
Hej Matilda =)

Good job on almost finishing the assignment! You're so close and if you want help you can just ask and I don't mind helping you.

<img width="257" alt="Screenshot 2021-02-15 at 16 55 16" src="https://user-images.githubusercontent.com/71715907/107968435-a8af8580-6fae-11eb-9a0b-562e1db01f75.png">

The first thing I saw on the website was that the drop-down list with options was missing all of the available options for the characters (for example purple hair and so on). These should be added in the HTML under the <select id="questions">

Second was an error generated in the console when the page ran: 
<img width="472" alt="Screenshot 2021-02-15 at 16 54 42" src="https://user-images.githubusercontent.com/71715907/107969158-ad286e00-6faf-11eb-8cb0-3bcc98196fe2.png">
There seems to be an issue with the attribute assigned on row 307. I think the issue may be that the eventListener for selectQuestion is based off a `change` command, and if you just guess brown hair when it first pops up in the list selectQuestion isn't run, but I'm not sure. 

Just let me know if anything is unclear or you want to discuss something!

2021-02-19 14:43 UTC, KarolCislowski requested changes
Hannah provided very good feedback for you. You need to fallow her suggestions and fix the issues that she pointed. 
1. You need to provide more filtering options. 
2. You need to assure that al filtering functions will reorganize your board.
3. You need to provide the last page with the result of the game.
Remember that you are not alone and there are friendly people on StackOverflow and Slack ready to help 😸

2021-02-19 14:43 UTC, KarolCislowski commented on code/script.js
> +  console.log(value, category);
Yes, all of the debugging console.log() statements should be removed at the end 😸

2021-05-31 05:06 UTC, KarolCislowski commented
Hello, it's your project. Do you remember me? I may be imperfect, but I believe you can still change that before you sit down to your final masterpiece!
![image](https://user-images.githubusercontent.com/50926159/120141019-f9ed2900-c1db-11eb-95df-db20da4f1088.png)

2021-06-04 08:03 UTC, matildasvensson85 commented
I made the changes now :)

2021-06-12 12:04 UTC, KarolCislowski approved these changes
Now it works great 👍🏻

2021-08-10 13:01 UTC, closed without merging